kind: pipeline
name: default

steps:
- name: build
  image: maven:3
  commads:
  - echo $JAVA_HOME
  - java -version
  - mvn compile
  
- name: test
  image: maven:3
  commands:
  - mvn clean install
